#!/bin/sh

# rockpack-mainsite - Use uwsgi to run rockpack wsgi web app.
#
# chkconfig: - 85 15
# description: Use uwsgi to run rockpack wsgi web app.
# processname: uwsgi


. /etc/rc.d/init.d/functions

NAME="`basename $0`"
USER=rockpack-mainsite
BIN=/usr/sbin/uwsgi
CFG=/etc/rockpack/mainsite/uwsgi.ini:rockpack
LOG=/var/log/$NAME.log
PID=/var/run/$NAME.pid
LOCK=/var/lock/subsys/$NAME
RETVAL=0

export ROCKPACK_SETTINGS=/etc/rockpack/mainsite/config.py

. /etc/rc.d/init.d/uwsgi-common
