"""Add most_influtential flag to video instance

Revision ID: 11f480b26722
Revises: c0943556082
Create Date: 2014-05-29 12:04:57.543404

"""

# revision identifiers, used by Alembic.
revision = '11f480b26722'
down_revision = 'c0943556082'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_instance', sa.Column('most_influential', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_instance', 'most_influential')
    ### end Alembic commands ###
