"""add is_favourite to videoinstance

Revision ID: 17d107c5dfb1
Revises: 40f545762e0d
Create Date: 2014-02-04 18:27:16.655576

"""

# revision identifiers, used by Alembic.
revision = '17d107c5dfb1'
down_revision = '40f545762e0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_instance', sa.Column('is_favourite', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_instance', 'is_favourite')
    ### end Alembic commands ###
