"""user promotions table

Revision ID: 1b2516ccffcc
Revises: 17d107c5dfb1
Create Date: 2014-02-20 19:25:57.088347

"""

# revision identifiers, used by Alembic.
revision = '1b2516ccffcc'
down_revision = '17d107c5dfb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=24), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['locale'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_promotion')
    ### end Alembic commands ###
