"""Add tags to video instance queue

Revision ID: 1de6cae29457
Revises: 68154013656
Create Date: 2014-05-08 17:07:31.042402

"""

# revision identifiers, used by Alembic.
revision = '1de6cae29457'
down_revision = '68154013656'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_instance_queue', sa.Column('tags', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_instance_queue', 'tags')
    ### end Alembic commands ###
