"""category on rockpackcoverart

Revision ID: 22031d3aca29
Revises: 22f155324df4
Create Date: 2013-04-16 17:48:00.604908

"""

# revision identifiers, used by Alembic.
revision = '22031d3aca29'
down_revision = '22f155324df4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rockpack_cover_art', sa.Column('category', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rockpack_cover_art', 'category')
    ### end Alembic commands ###
