"""subscriber_frequency

Revision ID: 25c5da6174ee
Revises: 3e86fe829c0c
Create Date: 2013-06-17 16:40:06.258283

"""

# revision identifiers, used by Alembic.
revision = '25c5da6174ee'
down_revision = '3506499d53b3'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('subscriber_frequency', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'subscriber_frequency')
    ### end Alembic commands ###
