"""channel.verified

Revision ID: 2b3ae0f23d4b
Revises: 51478120f7b3
Create Date: 2013-04-23 14:26:54.439154

"""

# revision identifiers, used by Alembic.
revision = '2b3ae0f23d4b'
down_revision = '51478120f7b3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'verified')
    ### end Alembic commands ###
