"""cover_aoi

Revision ID: 2d2011626632
Revises: 2b3ae0f23d4b
Create Date: 2013-04-26 11:10:17.221701

"""

# revision identifiers, used by Alembic.
revision = '2d2011626632'
down_revision = '2b3ae0f23d4b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rockpack_cover_art', sa.Column('cover_aoi', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('user_cover_art', sa.Column('cover_aoi', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('channel', sa.Column('cover_aoi', postgresql.ARRAY(sa.Float()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'cover_aoi')
    op.drop_column('user_cover_art', 'cover_aoi')
    op.drop_column('rockpack_cover_art', 'cover_aoi')
    ### end Alembic commands ###
