"""category on video_instance

Revision ID: 2fed29ce0178
Revises: 597c3c38ce0f
Create Date: 2013-03-27 12:35:17.067179

"""

# revision identifiers, used by Alembic.
revision = '2fed29ce0178'
down_revision = '597c3c38ce0f'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_instance_locale_meta',
            sa.Column('id', sa.CHAR(length=40), nullable=False),
            sa.Column('video_instance', sa.CHAR(length=24), nullable=False),
            sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
            sa.Column('star_count', sa.Integer(), server_default='0', nullable=False),
            sa.Column('date_added', sa.DateTime(), nullable=False),
            sa.Column('date_updated', sa.DateTime(), nullable=False),
            sa.Column('locale', sa.String(length=16), nullable=False),
            sa.ForeignKeyConstraint(['locale'], ['locale.id'], ),
            sa.ForeignKeyConstraint(['video_instance'], ['video_instance.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('locale','video_instance'),
            )
    op.execute('CREATE SEQUENCE video_instance_locale_meta_seq')
    op.execute('ALTER TABLE video_instance_locale_meta ALTER COLUMN id SET DEFAULT nextval(\'video_instance_locale_meta_seq\')')
    op.add_column('video', sa.Column('visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('video_instance',
            sa.Column('category', sa.Integer()),
            #sa.ForeignKeyConstraint(['category'], ['category.id'], ),
            )

    for locale in ('en-us', 'en-gb', 'en-us-x-demo', ):
        op.execute(""" UPDATE video_instance vi SET category = (
                        SELECT cat.id FROM channel c
                            JOIN video_instance i ON c.id = i.channel
                            JOIN video_locale_meta m ON m.video = i.video
                            JOIN video as v ON i.video = v.id
                            JOIN category as cat ON m.category = cat.id
                            WHERE i.id = vi.id
                            AND m.locale = '{}')
                        WHERE vi.category IS NULL""".format(locale))

    op.execute(""" INSERT INTO video_instance_locale_meta
                    (video_instance, locale, view_count, star_count, date_updated, date_added)
                        SELECT i.id, m.locale, m.view_count, m.star_count, m.date_updated, m.date_added FROM video v
                            JOIN video_locale_meta m ON m.video = v.id
                            JOIN video_instance i ON i.video = v.id""")

    op.execute("UPDATE video SET visible = false FROM video_locale_meta WHERE video_locale_meta.visible = true AND video_locale_meta.video = video.id")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_instance', 'category')
    op.drop_column('video', 'visible')
    op.drop_table('video_instance_locale_meta')
    op.execute('DROP SEQUENCE video_instance_locale_meta_seq')
    ### end Alembic commands ###
