"""new mood field

Revision ID: 31e916fa941e
Revises: 33a6396b051e
Create Date: 2014-01-17 17:08:49.592259

"""

# revision identifiers, used by Alembic.
revision = '31e916fa941e'
down_revision = '33a6396b051e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('display_name', sa.String(length=32), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood', 'display_name')
    ### end Alembic commands ###
