"""display_fullname on User

Revision ID: 32f0a39a1bb9
Revises: 48e3bc6b039e
Create Date: 2013-05-09 12:21:21.077706

"""

# revision identifiers, used by Alembic.
revision = '32f0a39a1bb9'
down_revision = '48e3bc6b039e'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_fullname', sa.Boolean(), server_default='true', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_fullname')
    ### end Alembic commands ###
