"""empty message

Revision ID: 33a6396b051e
Revises: 4bc3d359669d
Create Date: 2014-01-14 17:46:27.876037

"""

# revision identifiers, used by Alembic.
revision = '33a6396b051e'
down_revision = '4bc3d359669d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('link_title', sa.String(length=1024), nullable=True))
    op.add_column('video', sa.Column('link_url', sa.String(length=2048), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'link_url')
    op.drop_column('video', 'link_title')
    ### end Alembic commands ###
