"""Add is_influencer to User

Revision ID: 3c9885329fca
Revises: 11f480b26722
Create Date: 2014-06-25 16:42:30.939305

"""

# revision identifiers, used by Alembic.
revision = '3c9885329fca'
down_revision = '11f480b26722'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_influencer', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_influencer')
    ### end Alembic commands ###
