"""Added subscribe count fields

Revision ID: 3e3095f1b2a
Revises: 4a8bd38846f1
Create Date: 2013-04-09 19:16:35.031701

"""

# revision identifiers, used by Alembic.
revision = '3e3095f1b2a'
down_revision = '4a8bd38846f1'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('subscribe_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('channel_locale_meta', sa.Column('subscribe_count', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_locale_meta', 'subscribe_count')
    op.drop_column('channel', 'subscribe_count')
    
    ### end Alembic commands ###
