"""Add date_updated to video_instance

Revision ID: 3ed488e071a4
Revises: 58eaa9715323
Create Date: 2014-05-06 14:55:42.378910

"""

# revision identifiers, used by Alembic.
revision = '3ed488e071a4'
down_revision = '58eaa9715323'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_instance', sa.Column('date_updated', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_instance', 'date_updated')
    ### end Alembic commands ###
