"""category moved from meta to channel

Revision ID: 4a8bd38846f1
Revises: 2fed29ce0178
Create Date: 2013-04-08 13:41:00.539905

"""

# revision identifiers, used by Alembic.
revision = '4a8bd38846f1'
down_revision = '2fed29ce0178'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel',
        sa.Column('category', sa.Integer(), sa.ForeignKey('category.id'), nullable=True)
    )
    # Not dropping the column from meta (yet) for safety
    # op.drop_column('channel_locale_meta', u'category')

    op.execute(""" UPDATE channel c
                    SET category = m.category
                    FROM channel_locale_meta m
                    WHERE c.id = m.channel """)
    op.execute("ALTER TABLE channel_locale_meta ALTER COLUMN category DROP NOT NULL")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'category')
    ### end Alembic commands ###
