"""add mood table

Revision ID: 4a8edac4fed
Revises: 4bc3d359669d
Create Date: 2014-01-08 16:51:56.630656

"""

# revision identifiers, used by Alembic.
revision = '4a8edac4fed'
down_revision = '4bc3d359669d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    op.drop_table('mood')
