"""Add instance activity table

Revision ID: 4b5924754008
Revises: 1de6cae29457
Create Date: 2014-05-09 16:38:31.775184

"""

# revision identifiers, used by Alembic.
revision = '4b5924754008'
down_revision = '1de6cae29457'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_instance_anon_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_address', sa.String(length=15), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_instance_anon_activity')
    ### end Alembic commands ###
