"""Added channel.subscriber_count

Revision ID: 51478120f7b3
Revises: 22031d3aca29
Create Date: 2013-04-23 11:22:23.930389

"""

# revision identifiers, used by Alembic.
revision = '51478120f7b3'
down_revision = '22031d3aca29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('channel', sa.Column('star_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('channel', sa.Column('subscriber_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('channel_locale_meta', sa.Column('subscriber_count', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_locale_meta', 'subscriber_count')
    op.drop_column('channel', 'subscriber_count')
    op.drop_column('channel', 'star_count')
    op.drop_column('channel', 'view_count')
    ### end Alembic commands ###
