"""Migrate video_instance_locale_meta ids

Revision ID: 57cf562ea12
Revises: 2fed29ce0178
Create Date: 2013-04-10 18:17:44.841860

"""

# revision identifiers, used by Alembic.
revision = '57cf562ea12'
down_revision = '4a8bd38846f1'

from alembic import op
import sqlalchemy as sa

def upgrade():
    from rockpack.mainsite.services.video.models import VideoInstanceLocaleMeta
    from rockpack.mainsite.helpers.db import add_base64_pk
    from rockpack.mainsite.core.dbapi import db

    ### commands auto generated by Alembic - please adjust! ###
    query = VideoInstanceLocaleMeta.query.filter()
    total = query.count()
    step = 400
    for i in xrange(0, total, step):
        print 'group', i, 'step', step
        for v in query.offset(i).limit(step):
            v.id = None
            add_base64_pk(None, None, v, prefix='vl')
            db.session.add(v)
        db.session.commit()

    op.execute("DROP SEQUENCE video_instance_locale_meta_seq CASCADE")
    op.alter_column('video_instance_locale_meta', u'id',
               type_=sa.CHAR(length=24),
               nullable=False)

    ### end Alembic commands ###

def downgrade():
    pass
