"""Add deleted to video_instance

Revision ID: 58eaa9715323
Revises: 1de6cae29457
Create Date: 2014-04-29 11:16:52.254987

"""

# revision identifiers, used by Alembic.
revision = '58eaa9715323'
down_revision = '1de6cae29457'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_instance', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_instance', 'deleted')
    ### end Alembic commands ###
