"""baseline migration

Revision ID: 7d5deccb10f
Revises: None
Create Date: 2013-03-11 19:35:15.561571

"""

# revision identifiers, used by Alembic.
revision = '7d5deccb10f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('channel', sa.Column('public', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('external_token', u'expires',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('user', sa.Column('username_updated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('video_instance', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_instance', 'position')
    op.drop_column('user', 'username_updated')
    op.alter_column('external_token', u'expires',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('channel', 'public')
    op.drop_column('channel', 'deleted')
    ### end Alembic commands ###
