"""Added new date columns to channel and locale meta tables

Revision ID: b5e975c62e5
Revises: 7d5deccb10f
Create Date: 2013-03-13 11:40:31.550987

"""

# revision identifiers, used by Alembic.
revision = 'b5e975c62e5'
down_revision = '7d5deccb10f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False))
    op.add_column('channel', sa.Column('date_added', sa.DateTime(timezone=True), nullable=False))
    op.add_column('channel_locale_meta', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False))
    op.add_column('channel_locale_meta', sa.Column('date_added', sa.DateTime(timezone=True), nullable=False))
    op.add_column('video_locale_meta', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False))
    op.add_column('video_locale_meta', sa.Column('date_added', sa.DateTime(timezone=True), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_locale_meta', 'date_added')
    op.drop_column('video_locale_meta', 'date_updated')
    op.drop_column('channel_locale_meta', 'date_added')
    op.drop_column('channel_locale_meta', 'date_updated')
    op.drop_column('channel', 'date_added')
    op.drop_column('channel', 'date_updated')
    ### end Alembic commands ###
